Lab01/Models/DangKyModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab01.Models
{
    public class DangKyModel
    {
        public int id { get; set; }
        public string hoTen { get; set; }
        public DateTime ngaySinh { get; set; }

        public string Fhinh { get; set; }
    }
}

Lab01/Models/ErrorViewModel.cs
namespace Lab01.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab01/Models/MayTinhModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace Lab01.Models
{
    public class MayTinhModels
    {
        public double So1 { get; set; }
        public double So2 { get; set; }

        public string phepTinh { get; set; }

    }
}

Lab01/Controllers/DangKyController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Lab01.Models;


namespace Lab01.Controllers
{
    public class DangKyController : Controller
    {
        // khai báo
        private Microsoft.AspNetCore.Hosting.IHostingEnvironment hosting;
        public DangKyController(Microsoft.AspNetCore.Hosting.IHostingEnvironment _hosting)
        {
            hosting = _hosting;
        }
        public IActionResult Index()
        {
            return View();
        }
        //
        public IActionResult XuLyDangKy(DangKyModel m, IFormFile FHinh)
        {
            if (FHinh != null)
            {
                // Xử lý uploads
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(FHinh.FileName);
                string path = Path.Combine(hosting.WebRootPath, "images");
                using (var filestream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    // sao chép lên server
                    FHinh.CopyTo(filestream);
                }
                m.Fhinh = fileName;
            }

            return View(m);
        }
    }
}

Lab01/Controllers/HomeController.cs
using Lab01.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab01.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab01/Controllers/PhepTinhController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lab01.Models;

namespace Test.Controllers
{
    public class PhepTinhController : Controller
    {
        public IActionResult Index()

        {

            return View();
        }

        public IActionResult XuLy(MayTinhModels mt)
        {
            double ketQua = 0;
            switch (mt.phepTinh)
            {
                case "+":
                    ketQua = mt.So1 + mt.So2;
                    break;

                case "-":
                    ketQua = mt.So1 - mt.So2;
                    break;
                case "*":
                    ketQua = mt.So1 * mt.So2;
                    break;
                case "/":
                    ketQua = mt.So1 / mt.So2;
                    break;
                    //default:

                    //    break;
            }
            // ViewData["K"] = ketQua;
            ViewBag.KQ = ketQua;
            return View("Index");
        }
    }
}

Lab01/Views/DangKy/DangKy.cshtml
@model DangKyModel
<h1>Đăng ký thông tin</h1>
<br />
<div class="container p-5 my-5 border">
    <form method="post" asp-action="XuLyDangKy" enctype="multipart/form-data">

        <div class="form-group">
            <label>Họ tên</label>
            <input asp-for="hoTen" class="form-control" />
        </div>
        <br />
        <div class="form-group">
            <label>Ngày sinh</label>
            <input asp-for="ngaySinh" type="date" class="form-control" />
        </div>
        <div class="form-group">
            <label>Hình</label>
            <input name="Fhinh" type="file"  class="form-control" />
        </div>
        <br />
        <button type="submit" class="btn badge-success">Đăng ký</button>
    </form>
  
</div>

Lab01/Views/DangKy/Index.cshtml
@model DangKyModel
<h1>Đăng ký thông tin</h1>
<br />
<div class="container p-5 my-5 border">
    <form method="post" asp-action="XuLyDangKy" enctype="multipart/form-data">

        <div class="form-group">
            <label>Họ tên</label>
            <input asp-for="hoTen" class="form-control" />
        </div>
        <br />
        <div class="form-group">
            <label>Ngày sinh</label>
            <input asp-for="ngaySinh" type="date" class="form-control" />
        </div>
        <div class="form-group">
            <label>Hình</label>
            <input name="Fhinh" type="file" class="form-control" />
        </div>
        <br />
        <button type="submit" class="btn badge-success">Đăng ký</button>
    </form>

</div>

Lab01/Views/DangKy/XuLyDangKy.cshtml
@model DangKyModel
<h3>Thông tin đăng ký</h3>
<hr />
<ul>
    <li>Họ tên :@Model.hoTen</li>
    <li>Ngày sinh: @Model.ngaySinh</li>
    <li>Hình đại diện:@Model.Fhinh
    <br />
    <img src="/images/@Model.Fhinh" width="200px"/>
    </li>
</ul>

Lab01/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Lab01/Views/PhepTinh/Index.cshtml
@model MayTinhModels
<h1>PHÉP TÍNH ĐƠN GIẢN</h1>
<br />
<div class="container p-5 my-5 border">
    <form method="post" asp-action="XuLy">

        <div class="form-group">
            <label>Nhập số 1</label>
            <input asp-for="So1" class="form-control"/>
        </div>
        <br />
        <div class="form-group">
            <label>Nhập số 2</label>
            <input asp-for="So2" class="form-control"/>
        </div>
        <br />
        <div class="form-group">
            <lable>Chọn phép tính</lable>
            <select asp-for="phepTinh">
                <option value="+">Cộng</option>
                <option value="-">Trừ</option>
                <option value="*">Nhân</option>
                <option value="/">Chia</option>
            </select>
        </div>
        <br />
        <button type="submit" class="btn badge-success">Tính</button>
    </form>
    @if(ViewBag.KQ != null)
            {
                <h4>Kết quả: @ViewBag.KQ</h4>
            }
</div>

Lab01/Views/PhepTinh/XuLy.cshtml
Kết quả phép tính là ViewPag:@ViewBag.KQ

Lab01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab01.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab01</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PhepTinh" asp-action="Index">Tính toán</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DangKy" asp-action="Index">Đăng ký</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lab01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>